version: '3'
services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm # Recommended to avoid Chrome crashes

  test:
    build: .
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
